### ISSUE TITLE
Proxy Settings in SDK API

### ISSUE THREAD

**Issue by faisalbasra** [facebook/facebook-java-ads-sdk#15]
Is there any option to setup proxy settings in sdk/api, because most of organization have proxy server for Internet access. Thanks

**Comment by JiamingFB** [comment]
For now, you can modify the APIRequest.java file and add Proxy as argument to url.openConnection(). https://docs.oracle.com/javase/7/docs/api/java/net/URL.html#openConnection(java.net.Proxy)

I'm also working on decoupling network from other logic, so that you can customize it for your use case. The change will come with next version.

**Comment by faisalbasra** [comment]
Alright. I cloned and setup project in eclipse/inteliJ but getting errors "incompatible types" for many classes. Can you tell how I can checkout/setup sdk project. Thanks

**Comment by JiamingFB** [comment]
Hi, the source code can still be compiled by apache maven. You can install by following instructions on https://maven.apache.org/install.html

"incompatible types" is an issue that I'm working on right now. 
It's due to Java's type erasure implementation of generic and some compiler might not throw compilation errors. After type erasure, the parseResponse() function of APINode has the same signature as parseResponse() in subclasses, however List<APINode> is not a super class of List<[sub class]>.

**Comment by JiamingFB** [comment]
I have applied a temp fix to unblock development in IDE. You can pull the latest code. Meanwhile i'll try to figure out if there is a better way of resolving the issue. Thanks!

**Comment by JiamingFB** [comment]
The customization of sending GET/POST/DELETE requests is added in latest version, which can be used to change your network proxy. You can refer to example/NetworkCustomizationExample.java.

**Comment by faisalbasra** [comment]
Jiaming, can you add example how to set proxy with NetworkCustomizationExample.java because I can't find a way for adding proxy.

**Comment by bsheikh** [comment]
Can you elaborate on how to set the proxy? Looking through the `APIContext`, I don't see an option where the proxy can be added

**Comment by DavidFranck** [comment]
https://docs.oracle.com/javase/8/docs/technotes/guides/net/proxies.html
This doc may help you~
