### ISSUE TITLE
ClassCastException in weblogic - APIRequest.java

### ISSUE THREAD

**Issue by msooraj** [facebook/facebook-java-ads-sdk#39]
Please use HttpURLConnection instead of HttpsURLConnection. This is giving ClassCastException in weblogic. Working fine when I changed to HttpURLConnection .
You should never explicitly import/use Sun Java SE implementation specific classes in your code.

Link to similar issue:
http://stackoverflow.com/questions/3038026/using-java-class-httpsurlconnection

**Comment by JiamingFB** [comment]
Hi msooraj,

Initially we use HttpsURLConnection because we wanted to deal with certificate, but yes looks like that's no longer needed and will be cleaned.

I also found [this post](http://stackoverflow.com/questions/18512009/weblogic-net-http-soaphttpsurlconnection-cannot-be-cast-to-javax-net-ssl-httpsur) on stackoverflow and it might be helpful in your case. Basically try to do this in your server:
`set JAVA_OPTIONS=%JAVA_OPTIONS% -DUseSunHttpHandler=true`

Thanks!

**Comment by guxuoss** [comment]
close this as the issue has been resolved.
