### ISSUE TITLE
Update AdSet produces NPE

### ISSUE THREAD

**Issue by lashchenko** [facebook/facebook-java-ads-sdk#63]
Hi.

Following code throws `java.lang.NullPointerException`

```scala
val fbContext = new FbModel.FbApiContext(token)(ApplicationSecret)
fbContext.enableDebug(true)


val updateAdSet = new com.facebook.ads.sdk.AdSet(fbAdSetId, fbContext).update()
          .setStatus(cmpCampaign.toFbAdSetStatus)
          .setEndTime(cmpCampaign.toFbAdSetEndTime)
          .setDailyBudget(fbDailyBudget(fbAdInAdSet))
          .setTargeting(cmpCampaign.toFbTargeting)

try {
  updateAdSet.execute().getId
} catch {
  case e: Throwable => log.error(e)
}
```

Debug output presented below:
```
Response:
{"success":true}
========End of API Call========
[Warning] When parsing response, object is not consistent with JSON:
[JSON]{"success":true}
[Object]{}
java.lang.NullPointerException
```

**Comment by guxuoss** [comment]
For update, API do not return the id field by default.  You will not get id in the response.  Since we are doing converting it to string,  That's why it throws.  The warning message might be a little bit confusing and not critical.  We will fix it in later versions. 

https://github.com/facebook/facebook-java-ads-sdk/blob/master/src/main/java/com/facebook/ads/sdk/AdSet.java#L180

To access the id, you can setRedownload(true).
