### ISSUE TITLE
Adding CustomAudience users returns User

### ISSUE THREAD

**Issue by mdenison** [facebook/facebook-java-ads-sdk#65]
I'm looking into switching from the PHP to the Java ads SDK. 
This example https://github.com/facebook/facebook-java-ads-sdk/blob/master/examples/CustomAudienceExample.java shows how to add many users to a Custom Audience. (Pretty cool , since that is exactly what I looked for). 

The misleading part which I couldn't figure out is that:
```
use FacebookAds\Object\CustomAudience;
use FacebookAds\Object\Values\CustomAudienceTypes;

$emails = array(
  'test1@example.com',
  'test2@example.com',
  'test3@example.com',
);

$audience = new CustomAudience(<CUSTOM_AUDIENCE_ID>);

$audience->addUsers($emails, CustomAudienceTypes::EMAIL);
```

vs. 

```
User user = new CustomAudience(<CUSTOM_AUDIENCE_ID>, context).createUser()
  .setPayload("{\"schema\":\"EMAIL_SHA256\",\"data\":[\"9b431636bd164765d63c573c346708846af4f68fe3701a77a3bdd7e7e5166254\",\"8cc62c145cd0c6dc444168eaeb1b61b351f9b1809a579cc9b4c9e9d7213a39ee\",\"4eaf70b1f7a797962b9d2a533f122c8039012b31e0a52b34a426729319cb792a\"]}")
  .execute();
```

The Java ads SDK returns a User object. I couldn't figure out what kind of User is returned? I haven't tested anything yet, was just reading around the Documentation etc.

**Comment by mdenison** [comment]
After digging a little more into the code I found the missing pieces for my puzzle what kind of a User that is https://github.com/facebook/facebook-java-ads-sdk/blob/master/src/main/java/com/facebook/ads/sdk/CustomAudience.java#L1756 

But returning the head here doesn't make sense to me?

**Comment by daphyFB** [comment]
Hi, 

Thanks for reporting SDK bugs!

Yes I agree that just returning the head is not optimal. However, since there were not many operations for users (the other one being deleteUsers, which you can set filters to), I'd like to get more information of how you want to use this API and what your ultimate goal is (so we can prioritize and figure out a better solution).

I assume (please correct me if I'm wrong) you were looking into the php sdk example [here] (https://github.com/facebook/facebook-php-ads-sdk/blob/master/examples/custom_audiences.php) for this line:
`$audience->addUsers($emails, CustomAudienceTypes::EMAIL);`

However, I'm not able to find where you got the line:
`User user = new CustomAudience(<CUSTOM_AUDIENCE_ID>, context).createUser()`
Could you please tell me where this line is from?

And most importantly, do you intend to do more operations for those created users? 

Thanks for providing more information!

**Comment by mdenison** [comment]
Hey,

thanks for the quick reply.

This `User user = new CustomAudience(<CUSTOM_AUDIENCE_ID>, context).createUser()` is from the third example 'Ads API Java SDK': https://developers.facebook.com/docs/marketing-api/custom-audience-api/v2.8

At the moment we are not doing anything else with those users (also not planning to do so). 

For now I'll just ignore the return value. Once I've ported the first application I'll probably have more feedback!

**Comment by daphyFB** [comment]
Thanks a lot for the reply! Since there is no further use of the return value, and in other samples in the other two languages we don't use the return values either, we'll leave the SDK code as is. On the other hand, we will probably look into changing the sample code in the marketing-api to avoid future confusion. I'll close this issue for now; please reopen it if this doesn't meet your expectation.

We look forward to any more feedback :)
